apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: cassandra-dev
spec:
  template:
    metadata:
      labels:
        app: cassandra
        env: development
    spec:
      nodeSelector:
       env: development
      containers:
        - name: cassandra
          image: pmdcosta/cassandra:v8
          command:
            - /run.sh
          ports:
            - containerPort: 9042
              name: cql
            - containerPort: 9160
              name: thrift
          env:
            - name: MAX_HEAP_SIZE
              value: 512M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - mountPath: /cassandra_data
              name: data
      volumes:
        - name: data
          emptyDir: {}
