apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: cassandra
spec:
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      nodeSelector:
       env: development
      containers:
        - name: cassandra
          image: pmdcosta/cassandra:latest
          resources:
            limits:
              memory: "400Mi"
          ports:
            - containerPort: 9042
              name: cql
          env:
            - name: MAX_HEAP_SIZE
              value: 300M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - mountPath: /cassandra_data
              name: data
      volumes:
        - name: data
          emptyDir: {}
